steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/greenmail-337601/greenmile/my-image', '-f', '../', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/greenmail-337601/greenmile/my-image']
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['compute', 'instances', 'create-with-container', 'my-vm-name', '--container-image', 'gcr.io/greenmail-337601/greenmile/my-image']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'

- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']

- name: 'gcr.io/cloud-builders/yarn'
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml']