steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/greenmail-337601/greenmile/my-image', '.']

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/greenmail-337601/greenmile/my-image']
  
- name: node
  entrypoint: yarn
  args: ['install']
  dir: 'hello-world'
# - name: node
#   entrypoint: yarn
#   args: ['test']
#   dir: 'hello-world'
- name: node
  entrypoint: yarn
  args: ['run', 'build']
  env: [NODE_OPTIONS=--openssl-legacy-provider]
  dir: 'hello-world'


# - name: 'gcr.io/cloud-builders/yarn'
#   args: ['install']

# - name: 'gcr.io/cloud-builders/yarn'
#   args: ['run', 'build']

# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['app', 'deploy', 'app.yaml']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'